### ISSUE TITLE
Print P4Exceptions when reverting on workspace clean

### ISSUE THREAD

**Issue by k-dovgan** [Samsung/Universum#140] opened 2019-01-29 14:16 UTC
Originally created on Fri, 26 Jan 2018 17:03:46 +0200

Even though all exceptions on reverting should be ignored, if any happen they should be added to log for debugging.

**Comment by i-keliukh** [comment] 2019-09-21 06:35
This is a duplicate of #215

**Closed by i-keliukh** 2019-09-21 06:35 UTC
Labels: dev: exception handling, feature
